using System;
using System.Collections.Generic;
using System.Linq;

namespace Ademero.NucleusOneDotNetSdk.Model
{
    // Originally generated by nucleus_one_utilities.
    [Serializable]
    public class AssetItemTag : Common.Model.Entity<ApiModel.AssetItemTag>
    {
        private AssetItemTag(NucleusOneApp app) : base(app) { }

        public static AssetItemTag FromApiModel(ApiModel.AssetItemTag apiModel, NucleusOneApp app = null)
        {
            return new AssetItemTag(app)
            {
                AssetId = apiModel.AssetId,
                AssetName = apiModel.AssetName,
                AssetItemId = apiModel.AssetItemId,
                AssetItemName = apiModel.AssetItemName
            };
        }

        #region Properties

        public string AssetId { get; set; }

        public string AssetName { get; set; }

        public string AssetItemId { get; set; }

        public string AssetItemName { get; set; }

        #endregion

        public override ApiModel.AssetItemTag ToApiModel()
        {
            return new ApiModel.AssetItemTag()
            {
                AssetId = AssetId,
                AssetName = AssetName,
                AssetItemId = AssetItemId,
                AssetItemName = AssetItemName
            };
        }
    }

    [Serializable]
    public class AssetItemTagCollection
        : Common.Model.EntityCollection<AssetItemTag, ApiModel.AssetItemTagCollection>
    {
        public AssetItemTagCollection(
            AssetItemTag[] items,
            NucleusOneApp app = null
        ) : base(app, items) { }

        public static AssetItemTagCollection FromApiModel(
            ApiModel.AssetItemTagCollection apiModel,
            NucleusOneApp app = null
        )
        {
            return new AssetItemTagCollection(
                items: apiModel.AssetItemTags?.Select((x) => AssetItemTag.FromApiModel(x, app)).ToArray());
        }

        public override ApiModel.AssetItemTagCollection ToApiModel()
        {
            return new ApiModel.AssetItemTagCollection()
            {
                AssetItemTags = Items.Select((x) => x.ToApiModel()).ToArray()
            };
        }
    }
}
