using System;
using System.Linq;

namespace Ademero.NucleusOneDotNetSdk.Model
{
    // Originally generated by nucleus_one_utilities
    [Serializable]
    public class FieldListItem : Common.Model.Entity<ApiModel.FieldListItem>
    {
        private FieldListItem(NucleusOneApp app) : base(app) { }

        public static FieldListItem FromApiModel(ApiModel.FieldListItem apiModel, NucleusOneApp app = null)
        {
            return new FieldListItem(app)
            {
                Id = apiModel.Id,
                ParentValue = apiModel.ParentValue,
                Value = apiModel.Value 
            };
        }

        #region Properties

        public string Id { get; set; }

        public string ParentValue { get; set; }

        public string Value { get; set; }

        #endregion

        public override ApiModel.FieldListItem ToApiModel()
        {
            return new ApiModel.FieldListItem()
            {
                Id = Id,
                ParentValue = ParentValue,
                Value = Value
            };
        }
    }

    [Serializable]
    public class FieldListItemCollection : Common.Model.EntityCollection<FieldListItem, ApiModel.FieldListItemCollection>
    {
        public FieldListItemCollection(
            FieldListItem[] items,
            NucleusOneApp app = null
        ) : base(app, items) { }

        public static FieldListItemCollection FromApiModel(
            ApiModel.FieldListItemCollection apiModel,
            NucleusOneApp app = null
        )
        {
            return new FieldListItemCollection(
                items: apiModel.FieldListItems?.Select((x) => FieldListItem.FromApiModel(x, app)).ToArray());
        }

        public override ApiModel.FieldListItemCollection ToApiModel()
        {
            return new ApiModel.FieldListItemCollection()
            {
                FieldListItems = Items.Select((x) => x.ToApiModel()).ToArray()
            };
        }
    }
}