using System;
using System.Linq;

namespace Ademero.NucleusOneDotNetSdk.Model
{
    // Originally generated by nucleus_one_utilities.
    [Serializable]
    public class ProjectAccessAssignments : Common.Model.Entity<ApiModel.ProjectAccessAssignments>
    {
        private ProjectAccessAssignments(NucleusOneApp app) : base(app) { }

        public static ProjectAccessAssignments FromApiModel(
            ApiModel.ProjectAccessAssignments apiModel,
            NucleusOneApp app = null
        )
        {
            if (apiModel == null)
                return null;
            return new ProjectAccessAssignments(app)
            {
                Tasks = apiModel.Tasks,
                Approvals = apiModel.Approvals,
                DocumentFolders = apiModel.DocumentFolders
            };
        }

        #region Properties

        public string Tasks { get; set; }
        public string Approvals { get; set; }
        public string DocumentFolders { get; set; }

        #endregion

        public override ApiModel.ProjectAccessAssignments ToApiModel()
        {
            return new ApiModel.ProjectAccessAssignments()
            {
                Tasks = Tasks,
                Approvals = Approvals,
                DocumentFolders = DocumentFolders
        };
        }
    }

    [Serializable]
    public class ProjectAccessAssignmentsCollection
        : Common.Model.EntityCollection<ProjectAccessAssignments, ApiModel.ProjectAccessAssignmentsCollection>
    {
        public ProjectAccessAssignmentsCollection(
            ProjectAccessAssignments[] items,
            NucleusOneApp app = null
        ) : base(app, items) { }

        public static ProjectAccessAssignmentsCollection FromApiModel(
            ApiModel.ProjectAccessAssignmentsCollection apiModel,
            NucleusOneApp app = null
        )
        {
            if (apiModel == null)
                return null;
            return new ProjectAccessAssignmentsCollection(
                items: apiModel.ProjectAccessAssignmentss?.Select((x) => ProjectAccessAssignments.FromApiModel(x, app)).ToArray());
        }

        public override ApiModel.ProjectAccessAssignmentsCollection ToApiModel()
        {
            return new ApiModel.ProjectAccessAssignmentsCollection()
            {
                ProjectAccessAssignmentss = Items.Select((x) => x.ToApiModel()).ToArray()
            };
        }
    }
}
