using Newtonsoft.Json;
using System;

namespace Ademero.NucleusOneDotNetSdk.ApiModel
{
    // Originally generated by nucleus_one_utilities
    // Serializable members must be explicitly marked with [JsonProperty].
    [Serializable]
    [JsonObject(MemberSerialization.OptIn, ItemNullValueHandling = NullValueHandling.Ignore)]
    public class FieldListItem : Common.ApiModel.Entity<FieldListItem>
    {
        #region Properties

        [JsonProperty("ID")]
        public string Id { get; set; }

        [JsonProperty("ParentValue")]
        public string ParentValue { get; set; }

        [JsonProperty("Value")]
        public string Value { get; set; }

        #endregion
    }

    // Originally generated by nucleus_one_utilities
    // Serializable members must be explicitly marked with [JsonProperty].
    [Serializable]
    [JsonObject(MemberSerialization.OptIn, ItemNullValueHandling = NullValueHandling.Ignore)]
    public class FieldListItemCollection : QueryResultEntityCollection<FieldListItemCollection, FieldListItem>
    {
        #region Properties

        public FieldListItem[] FieldListItems
        {
            get => Items;
            set => Items = value;
        }

        #endregion
    }
}
