using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace Ademero.NucleusOneDotNetSdk.ApiModel
{
    // Originally generated by nucleus_one_utilities
    // Serializable members must be explicitly marked with [JsonProperty].
    [Serializable]
    [JsonObject(MemberSerialization.OptIn, ItemNullValueHandling = NullValueHandling.Ignore)]
    public class ProjectMemberAccess : Common.ApiModel.Entity<ProjectMemberAccess>
    {
        public ProjectMemberAccess() { }

        #region Properties

        [JsonProperty("Tasks")]
        public string Tasks { get; set; }

        [JsonProperty("Approvals")]
        public string Approvals { get; set; }

        [JsonProperty("DocumentFolders")]
        public string DocumentFolders { get; set; }

        [JsonProperty("AssetItems")]
        public string AssetItems { get; set; }

        #endregion
    }

    // Serializable members must be explicitly marked with [JsonProperty].
    [Serializable]
    [JsonObject(MemberSerialization.OptIn, ItemNullValueHandling = NullValueHandling.Ignore)]
    public class ProjectMemberAccessCollection : QueryResultEntityCollection<ProjectMemberAccessCollection, ProjectMemberAccess>
    {
        public ProjectMemberAccessCollection() { }

        #region Properties

        [JsonProperty("ProjectMemberAccesss")]
        public ProjectMemberAccess[] ProjectMemberAccesss
        {
            get => Items;
            set => Items = value;
        }

        #endregion
    }
}
