using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace Ademero.NucleusOneDotNetSdk.ApiModel
{
    // Originally generated by nucleus_one_utilities
    // Serializable members must be explicitly marked with [JsonProperty].
    [Serializable]
    [JsonObject(MemberSerialization.OptIn, ItemNullValueHandling = NullValueHandling.Ignore)]
    public class ProjectAccess : Common.ApiModel.Entity<ProjectAccess>
    {
        public ProjectAccess() { }

        #region Properties

        [JsonProperty("Assignments")]
        public ProjectAccessAssignments Assignments { get; set; }

        [JsonProperty("MemberAccess")]
        public ProjectMemberAccess MemberAccess { get; set; }

        #endregion
    }

    // Originally generated by nucleus_one_utilities
    // Serializable members must be explicitly marked with [JsonProperty].
    [Serializable]
    [JsonObject(MemberSerialization.OptIn, ItemNullValueHandling = NullValueHandling.Ignore)]
    public class ProjectAccessCollection : QueryResultEntityCollection<ProjectAccessCollection, ProjectAccess>
    {
        public ProjectAccessCollection() { }

        #region Properties

        [JsonProperty("ProjectAccesss")]
        public ProjectAccess[] ProjectAccesss { get; set; }

        #endregion
    }
}
