using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace Ademero.NucleusOneDotNetSdk.ApiModel
{
    // Originally generated by nucleus_one_utilities
    // Serializable members must be explicitly marked with [JsonProperty].
    [Serializable]
    [JsonObject(MemberSerialization.OptIn, ItemNullValueHandling = NullValueHandling.Ignore)]
    public class ProjectAccessAssignments : Common.ApiModel.Entity<ProjectAccessAssignments>
    {
        public ProjectAccessAssignments() { }

        #region Properties

        [JsonProperty("Tasks")]
        public string Tasks { get; set; }

        [JsonProperty("Approvals")]
        public string Approvals { get; set; }

        [JsonProperty("DocumentFolders")]
        public string DocumentFolders { get; set; }

        #endregion
    }

    // Serializable members must be explicitly marked with [JsonProperty].
    [Serializable]
    [JsonObject(MemberSerialization.OptIn, ItemNullValueHandling = NullValueHandling.Ignore)]
    public class ProjectAccessAssignmentsCollection : QueryResultEntityCollection<ProjectAccessAssignmentsCollection, ProjectAccessAssignments>
    {
        public ProjectAccessAssignmentsCollection() { }

        #region Properties

        [JsonProperty("ProjectAccessAssignmentss")]
        public ProjectAccessAssignments[] ProjectAccessAssignmentss
        {
            get => Items;
            set => Items = value;
        }

        #endregion
    }
}
