using Newtonsoft.Json;
using System;

namespace Ademero.NucleusOneDotNetSdk.ApiModel
{
    [Serializable]
    [JsonObject(MemberSerialization.OptIn, ItemNullValueHandling = NullValueHandling.Ignore)]
    public class Tag : Common.ApiModel.Entity<Tag>
    {
        public Tag() { }

        #region Properties

        [JsonProperty("Text")]
        public string Text { get; set; }

        [JsonProperty("TextLower")]
        public string TextLower { get; set; }

        [JsonProperty("ModifiedOn")]
        public string ModifiedOn { get; set; }

        [JsonProperty("AssetItemTag")]
        public AssetItemTag AssetItemTag { get; set; }

        #endregion
    }

    // Originally generated by nucleus_one_utilities
    // Serializable members must be explicitly marked with [JsonProperty].
    [Serializable]
    [JsonObject(MemberSerialization.OptIn, ItemNullValueHandling = NullValueHandling.Ignore)]
    public class TagCollection : QueryResultEntityCollection<TagCollection, Tag>
    {
        public TagCollection() { }

        #region Properties

        [JsonProperty(nameof(Tags))]
        public Tag[] Tags
        {
            get => Items;
            set => Items = value;
        }

        #endregion
    }
}
